### ISSUE TITLE
is possible test locally in ubuntu 20?

### ISSUE THREAD

**Issue by johnfelipe** [groupdocs-translation-cloud/groupdocs-translation-cloud-python#1]

**Comment by johnfelipe** [comment]
from groupdocstranslationcloud.configuration import Configuration
	from groupdocstranslationcloud.api.storage_api import StorageApi

	# enter valid client_secret and client_id
	configuration = Configuration(client_secret="fdsfasdgasdg", client_id="fdsd-7543-43fb-dasf-asdfasdf")

	# enter path to file on storage
	path = "https://api.groupdocs.cloud/v1.0/translation/storage/folder/installation?storageName=traducciones"
	api = StorageApi(configuration)
	res = api.download_file(path)
	print(res)

this is log

	root@ubuntu21:~/groupdocs-translation-cloud-python/markdown# python3 translation_python_download_file.py
	Traceback (most recent call last):
	  File "/root/groupdocs-translation-cloud-python/markdown/translation_python_download_file.py", line 10, in <module>
		res = api.download_file(path)
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/api/storage_api.py", line 573, in download_file
		(data) = self.__download_file_with_http_info(path, **kwargs)
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/api/storage_api.py", line 635, in __download_file_with_http_info
		return self.api_client.call_api('/storage/file/{path}', 'GET', path_params, query_params, header_params,
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/api_client.py", line 327, in call_api
		return self.__call_api(resource_path, method, path_params, query_params, header_params,
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/api_client.py", line 158, in __call_api
		response_data = self.request(method, url, query_params=query_params, headers=header_params,
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/api_client.py", line 342, in request
		return self.rest_client.GET(url,
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/rest.py", line 246, in GET
		return self.request("GET", url,
	  File "/usr/local/lib/python3.9/dist-packages/groupdocstranslationcloud/rest.py", line 240, in request
		raise ApiException(http_resp=r)
	groupdocstranslationcloud.rest.ApiException: (404)
	Reason: Not Found
	HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 08 Jun 2022 01:50:17 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Kestrel', 'Strict-Transport-Security': 'max-age=2592000'})
	HTTP response body: b'{"requestId":"2f5b701d-5279-4a29-b5d9-1c5e68a4ac8e","error":{"code":"errorAmazonS3Storage","message":"AmazonS3 Storage exception: The specified key does not exist. Bucket \'groupdocs.cloud-filestorage-prod\', FilePath \'909431/5463c366-3510-4dd1-adf6-ab955ce28994/https:/api.groupdocs.cloud/v1.0/translation/storage/folder/installation?storageName=traducciones\'","description":"Operation Failed. Exception of type \'Amazon.Runtime.Internal.HttpErrorResponseException\' was thrown.","dateTime":"2022-06-08T01:50:17.5098803Z","innerError":null}}'

how solve this?
